- name: Add apt key Google Chrome
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present 

- name: Add Repos Google Chrome
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google
    update_cache: yes

- name: Create apt keyrings dir Microosft
  become: true
  ansible.builtin.file:
    path: '/etc/apt/keyrings'
    state: directory
    mode: 'u=rwx,go=rx'

- name: Install key Microsoft
  become: true
  ansible.builtin.get_url:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    dest: '/etc/apt/keyrings/'
    mode: 'u=rw,go=r'
    force: true

- name: Install repo MS Edge
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/edge stable main"
    state: present
    filename: vscode

- name: Install Brownsers Packages 
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
    update_cache: yes
  vars:
    packages:
      - google-chrome-stable
      - microsoft-edge-stable